default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: employee_manage_development

test:
  <<: *default
  database: employee_manage_test

production:
  <<: *default
  database: employee_manage_production